version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: username   
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: youtube_videos   
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build:
        context: .  
    image: trademarkia
    container_name: trademarkia
    ports:
      - "3000:3000"  
    env_file:
     - local.env
    
    environment:
      POSTGRES_HOST: postgres
    
    depends_on:
      - postgres        


volumes:
  postgres_data:
    driver: local



